import Head from 'next/head'
// import Image from 'next/image'
import { Barlow_Semi_Condensed } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Circle, Flex, Grid, GridItem, HStack, Image, Box, Text } from '@chakra-ui/react'

const barlow = Barlow_Semi_Condensed({weight:['500','600'], subsets: ['latin'] })

const Testimoni = ({bg,rows,cols, name,teks1, teks2})=>{
  const clr = bg == "brand.white"? "brand.greyBlue": "brand.white";
  return <GridItem borderRadius='10px' p='30px'
              rowSpan={rows} colSpan={cols} 
              bg={bg} color={clr}>
            <HStack spacing="20px">
              <Circle size="40px">
                <Image src={`/images/image-${name.toLowerCase().split(' ')[0]}.jpg`} alt={name} borderRadius={50} />
              </Circle>
              <Box>
                <Text>{name}</Text>
                <Text opacity={0.5}>Verified Graduate</Text>
              </Box>
            </HStack>
            <Text fontSize='18px' my="20px">{teks1} </Text>
            <Text opacity={0.7}>{teks2}</Text>
          </GridItem>
}
export default function Home() {
  return (
    <>
      <Head>
        <title>Testimonials Grid Section</title>
        <meta name="description" content="Generated by Nida Nido" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={barlow.className}>
        <Flex w='100vw' h={{base:'100%', sm:'100vh'}} bg="brand.lightGreyBlue"
        flexDir='column' justifyContent='center' alignItems='center' py={{base:'45px', sm:0}}
         >
          <Grid h={{sm:'600px'}} w={{base:"90%", sm:"1000px"}}
                templateRows={{base:'repeat(8, 1fr)', sm:"repeat(2, 1fr)"}}
                templateColumns={{base:"repeat(1, 1fr)", sm:"repeat(4, 1fr)"}}
                gap={4} color="brand.white" fontSize='13px' >
            
            <Testimoni bg="brand.violet" rows={{base:2, sm:1}} cols={{base:1, sm:2}} name="Daniel Clifford"
                teks1={`I received a job offer mid-course, and the subjects I learned were current, if not more so, in the company I joined. I honestly feel I got every penny’s worth. `}
                teks2={`“ I was an EMT for many years before I joined the bootcamp. I’ve been looking to make a transition and have heard some people who had an amazing experience here. I signed up for the free intro course and found it incredibly fun! I enrolled shortly thereafter. The next 12 weeks was the best - and most grueling - time of my life. Since completing the course, I’ve successfully switched careers, working as a Software Engineer at a VR startup. ”`}
                   />
            <Testimoni bg="brand.greyBlue" rows={{base:1, sm:1}} cols={{base:1, sm:1}} name="Jonathan Walters"
                teks1={`The team was very supportive and kept me motivated`}
                teks2={`“ I started as a total newbie with virtually no coding skills. I now work as a mobile engineer for a big company. This was one of the best investments I’ve made in myself. ”`}
                   />
            <Testimoni bg="brand.white" rows={{base:2, sm:2}} cols={{base:1, sm:1}} name="Kira Whittle"
                teks1={`Such a life-changing experience. Highly recommended!`}
                teks2={`“ Before joining the bootcamp, I’ve never written a line of code. I needed some structure from professionals who can help me learn programming step by step. I was encouraged to enroll by a former student of theirs who can only say wonderful things about the program. The entire curriculum and staff did not disappoint. They were very hands-on and I never had to wait long for assistance. The agile team project, in particular, was outstanding. It took my learning to the next level in a way that no tutorial could ever have. In fact, I’ve often referred to it during interviews as an example of my developent experience. It certainly helped me land a job as a full-stack developer after receiving multiple offers. 100% recommend! ”`}
                   />
            <Testimoni bg="brand.white" rows={{base:1, sm:1}} cols={{base:1, sm:1}} name="Jeanette Harmon"
                teks1={`An overall wonderful and rewarding experience`}
                teks2={`“ Thank you for the wonderful experience! I now have a job I really enjoy, and make a good living while doing something I love. ”`}
                   />
            <Testimoni bg="brand.blackBlue" rows={{base:2, sm:1}} cols={{base:1, sm:2}} name="Patrick Abrams"
                teks1={`Awesome teaching support from TAs who did the bootcamp themselves. Getting guidance from them and learning from their experiences was easy.`}
                teks2={`“ The staff seem genuinely concerned about my progress which I find really refreshing. The program gave me the confidence necessary to be able to go out in the world and present myself as a capable junior developer. The standard is above the rest. You will get the personal attention you need from an incredible community of smart and amazing people. ”`}
                   />

          </Grid>
        </Flex>
      </main>
    </>
  )
}
